In [2]:
#just python basics
print("time to learn pytorch")

time to learn pytorch


In [3]:
!nvidia-smi

Sun Jan  4 16:40:54 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu126


In [5]:
#tensors are a generalization of a data structures like scalar, vectors, matrices so we don't change their names due to their dimensionality
#creating tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
vector = torch.tensor([2,2])
print(vector.ndim)
print(vector.shape)
print(vector)


1
torch.Size([2])
tensor([2, 2])


In [9]:
#Matrix and tensors. Matrices are just 2 dimensional tensors as tensors are the generalized term for n dimensional data structures
matrix = torch.tensor([[7,8],[2,3],[3,4]])
print(matrix.ndim)
print(matrix.shape)
print(matrix)
matrix2 = torch.tensor([[1,2],[3,4]])
print(matrix2.ndim)
print(matrix2.shape)
print(matrix2)

2
torch.Size([3, 2])
tensor([[7, 8],
        [2, 3],
        [3, 4]])
2
torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


In [10]:
tensor = torch.tensor([[[1,2,3],[2,3,4],[2,3,4]]])
print(tensor.ndim)
print(tensor.shape)
print(tensor)

3
torch.Size([1, 3, 3])
tensor([[[1, 2, 3],
         [2, 3, 4],
         [2, 3, 4]]])


In [11]:
#One of the common pitfalls apparently is that we access the wrong rank of our tensor
print(tensor[0])
#compare that with
print('\n')
print(tensor[0][0])

tensor([[1, 2, 3],
        [2, 3, 4],
        [2, 3, 4]])


tensor([1, 2, 3])


In [12]:
random_tensor = torch.rand(3,4)
#create a random tensor with 3 rows and 4 columns
#useful for the starting tensors for neural networks.
print(random_tensor)

tensor([[0.3927, 0.3696, 0.2150, 0.1285],
        [0.5204, 0.7215, 0.7642, 0.2362],
        [0.1708, 0.4326, 0.7352, 0.9223]])


In [13]:
## zeroes and ones, zeroes is useful to mask bits
zero = torch.zeros(3,1)
print(zero * random_tensor)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [14]:
#ones explanation was skipped as they're solemnly used
ones = torch.ones(3,4)

In [15]:
one_to_ten = torch.arange(1,11,1) #it takes, start, end, steps, it's similar to the range() function in python
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#tensors.'x'_like method returns a ones or zeroes  tensor that has the same shape as the input tensor with the values there.
zeroeslike = torch.zeros_like(one_to_ten)
zeroeslike

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
#tensors with specific datatypes, the tensor creating methods take in the dtype argument to specify the dtype. The specific name for the dtypes you can just look up
float32tensor = torch.tensor([[3.0,34,3.3],[23,4,4]],
                             dtype = None,
                             device=None,
                             requires_grad=False)
float32tensor.dtype

torch.float32

##Big 3 Errors we'll probably run in with Tensor Attributes
1. tensors with not the right datatype (verify with tensor.dtype)
2. tensors not right shape (verify with tensor.shape)
3. tensors not on right device (verify with tensor.device)


##other things
1. surprisingly a lot of int * floats do work but we just have to know that this could cause issues
2. devices refer to GPU and CPU

In [18]:
#we can typecase tensors using the following. 'tensorname.type(dtype)'
float16 = float32tensor.type(torch.float16)
float16.dtype


torch.float16

In [19]:
float16.device
float16.shape

torch.Size([2, 3])

##Operations
add, sub, multiply(element wise), divide, matrix multiplication.
total of 5 multiplications. Matrix multiplication and normal multiplication depend on the rank of the tensor.
. if we add/sub/multiply/divide a tensor it will do the operation so for all elements. So there goes 4 cases.
. Matrix Multiplications are matrix multiplications/dot products are shown in the second cell below

In [20]:
#operations are done twice to show diff ways of doing so
tensor = torch.arange(0,6)
print(tensor)
print('\n')
print(tensor +10)
print(torch.add(tensor,10))
print('\n')
print(tensor -10)
print(torch.sub(tensor,10))
print('\n')
print(tensor *10)
print(torch.mul(tensor,10))
print('\n')
print(tensor /10)
print(torch.div(tensor,10))

tensor([0, 1, 2, 3, 4, 5])


tensor([10, 11, 12, 13, 14, 15])
tensor([10, 11, 12, 13, 14, 15])


tensor([-10,  -9,  -8,  -7,  -6,  -5])
tensor([-10,  -9,  -8,  -7,  -6,  -5])


tensor([ 0, 10, 20, 30, 40, 50])
tensor([ 0, 10, 20, 30, 40, 50])


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000])


In [21]:
#dot products/matrix multiplications are done in pytorch using the following
matrixA = torch.tensor([[1,2,3,4,5],[1,2,3,4,5]])
matrixB = torch.tensor([[1,2],
                        [3,4],
                        [5,6],
                        [7,8],
                        [9,0]])

print(matrixA.shape,matrixB.shape)
print('See how inner dimensions match but the shape is from the outer dimensions, that must follow broadcasting rules ')
print('\n')
print(torch.matmul(matrixA,matrixB)) #this is matrix multiplication
print(torch.mm(matrixA,matrixB)) #this is matrix multiplication
print(matrixA @ matrixB) #this is matrix multiplication

torch.Size([2, 5]) torch.Size([5, 2])
See how inner dimensions match but the shape is from the outer dimensions, that must follow broadcasting rules 


tensor([[95, 60],
        [95, 60]])
tensor([[95, 60],
        [95, 60]])
tensor([[95, 60],
        [95, 60]])


In [22]:
%%time
print(torch.matmul(matrixA,matrixB)) #this is matrix multiplication

tensor([[95, 60],
        [95, 60]])
CPU times: user 823 µs, sys: 120 µs, total: 943 µs
Wall time: 764 µs


In [23]:
%%time
print(matrixA @ matrixB) #this is matrix multiplication

tensor([[95, 60],
        [95, 60]])
CPU times: user 394 µs, sys: 896 µs, total: 1.29 ms
Wall time: 1.76 ms


Seems lilke using @ or matmul makes little difference on the time.

##Just as a easy heuristic for shape mismatch errors:
1. use .shape() and the shapes of the inner dimensions must match, in addition the outer dimensions will determine the shape of the matrix
2. If we have 2 tensors of the same shape, take the transpose of 1 to multiply them. This is shown below

In [24]:
matrixC = torch.rand(3,4)
matrixD = torch.rand(3,4)
print(f'matrix C is {matrixC}')
print(f'matrix D is {matrixD}')
print('\n')
#print(matrixC @ matrixD) <<--- causes error
matrixD2 = matrixD.T
print(f'multiplied we have {matrixC @ matrixD2} because we took the transpose of D')

matrix C is tensor([[0.4095, 0.5138, 0.8089, 0.9733],
        [0.9166, 0.1837, 0.5434, 0.8315],
        [0.9144, 0.7061, 0.8320, 0.8387]])
matrix D is tensor([[0.6526, 0.9107, 0.4113, 0.6277],
        [0.5294, 0.3666, 0.6312, 0.4884],
        [0.2552, 0.1025, 0.1195, 0.3613]])


multiplied we have tensor([[1.6789, 1.3912, 0.6055],
        [1.5109, 1.3018, 0.6181],
        [2.1085, 1.6778, 0.7081]]) because we took the transpose of D


##Finding Tensor's Descriptive statistics (min, max,  mean, sum etc) + aggregation

In [25]:
x = torch.arange(0,100,10)

## .min .max .sum .mean all work, below are different ways to use them. note that mean only works on Long datatypes in torch.  

In [26]:
print(x.min(), torch.min(x), x.max(), torch.max(x), x.type(torch.float32).mean(), torch.mean(x.type(torch.float32)), x.sum(), torch.sum(x))

tensor(0) tensor(0) tensor(90) tensor(90) tensor(45.) tensor(45.) tensor(450) tensor(450)


## argmin and argmax finds the smallest and largets values' positions, useful for softmax layers

In [27]:
print(x.argmin(), x.argmax())

tensor(0) tensor(9)


## Reshaping, Viewing, Stacking, Squeezing, Permuting Tensors
1. reshaping reshapes a tensors' dimensions (for matrix mult)
2. viewing prints the tensor in a given shape but doesn't change it in memory, but assigning a variable to a view of a  tensor makes the variable point to the tensor in memory.
3. Stacking stacks tensors vertically or horizontally, hence vstack and hstack
4. Squeezing removes all '1' dimensions in a tensor
5. Unqueezing adds a '1' dimension
6. Permute prints a tensor with permuted (swapped) dimensions, using permute also references the original tensor


In [28]:
t  = torch.arange(1,101)
t_reshaped = t.reshape(1,10,10) #remember, just like pandas, tensor dimensions must be compatible. A good rule of thumb is factors of the tocal dimensions
print(t_reshaped)

tensor([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
         [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
         [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
         [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])


In [29]:
tv = t.view(10,1,10)
tv

tensor([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]],

        [[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]],

        [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

        [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70]],

        [[ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])

In [30]:
#here's an example of stack.
tstack = torch.stack([t,t,t,t],dim=0)
t

tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100])

In [31]:
#here's squeeze and unsqueeze
#t_reshaped is our tensor that's dimension 1,10,10
print(t_reshaped)
print('Here\'s t_reshaped squeezed\n')
print(t_reshaped.squeeze())
print('Here\'s t_reshaped unsqueezed\n')
print(t_reshaped.unsqueeze(dim=0))
#

tensor([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
         [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
         [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
         [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])
Here's t_reshaped squeezed

tensor([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],


In [32]:
#permute usage is when dimensions have a meaning, It does conceptually different this to reshape
#remember t_reshaped had dimensions (1,10,10) so if we want to change it to 10 1 10 we switch it the following way, however notice it's different depending on the order of the nth rank
tp = t_reshaped.permute(1,0,2)
print(tp)
tp2 = t_reshaped.permute(2,0,1)
print(tp2)

tensor([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]],

        [[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50]],

        [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60]],

        [[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70]],

        [[ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]]])
tensor([[[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91]],

        [[  2,  12,  22,  32,  42,  52,  62,  72,  82,  92]],

        [[  3,  13,  23,  33,  43,  53,  63,  73,  83,  93]],

        [[  4,  14,  24,  34,  44,  54,  64,  74,  84,  94]],

        [[  5,  15,  25,  35,  45,  55,  65,  75,  85,  95]],

        [[  6,  16,  26,  36,  46,  56,  66,  76,  86, 

##typecasting between numpy and torch tensors
It has it's specific uses

In [33]:
##Here's how it's done
import numpy as np
#numpy -> tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
print(array,tensor)

print('\n')
#torch -> numpy
testt =  torch.arange(1,10)
testa = testt.numpy()
print(testt, testa)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) [1 2 3 4 5 6 7 8 9]


##Reproducibility and seeding

In [34]:
#This is how we seed experiments
seed = 42
torch.manual_seed(seed)
#that's it
rand_t  = torch.randn(4,4)
rand_t
#note that it only lives in the same cell

tensor([[ 1.9269,  1.4873,  0.9007, -2.1055],
        [ 0.6784, -1.2345, -0.0431, -1.6047],
        [-0.7521,  1.6487, -0.3925, -1.4036],
        [-0.7279, -0.5594, -0.7688,  0.7624]])

In [35]:
#this should remain randomn
rand_t  = torch.randn(4,4)
rand_t

tensor([[ 1.6423, -0.1596, -0.4974,  0.4396],
        [-0.7581,  1.0783,  0.8008,  1.6806],
        [ 1.2791,  1.2964,  0.6105,  1.3347],
        [-0.2316,  0.0418, -0.2516,  0.8599]])

##Ensuring correct device usage and device agnostic code

In [51]:
#this is device agnostic code.
torch.cuda.is_available()

True

In [36]:
#surprisingly useful, we set a device variable to choose the gpu if available
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [37]:
tensor = torch.tensor([1,2,3,4])
tensor.device
#default is cpu

device(type='cpu')

In [40]:
tensor = torch.tensor([1,2,3,4], device='cuda')
tensor.device
#we can change it to gpu

device(type='cuda', index=0)

In [41]:
#or move them around using our device variable as convenient
tensor = torch.tensor([1,2,3,4])
print(tensor.device)
gputens = tensor.to(device)
print(gputens.device)
#'0' is the index of the  gpu in case we are using multiple gpus.

cpu
cuda:0


#Keep in mind numpy does not work on cpus so here are some methods to use to change tensors into numpy arrays by moving them to the cpu first

In [42]:
gputens.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [47]:
print(gputens.cpu().numpy())
#now it works. easy enough
gputens.device

[1 2 3 4]


device(type='cuda', index=0)