In [34]:
#just python basics
print("time to learn pytorch")

Time to learn pytorch


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [35]:
#tensors are a generalization of a data structures like scalar, vectors, matrices so we don't change their names due to their dimensionality
#creating tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [21]:
vector = torch.tensor([2,2])
print(vector.ndim)
print(vector.shape)
print(vector)


1
torch.Size([2])
tensor([2, 2])


In [20]:
#Matrix and tensors. Matrices are just 2 dimensional tensors as tensors are the generalized term for n dimensional data structures
matrix = torch.tensor([[7,8],[2,3],[3,4]])
print(matrix.ndim)
print(matrix.shape)
print(matrix)
matrix2 = torch.tensor([[1,2],[3,4]])
print(matrix2.ndim)
print(matrix2.shape)
print(matrix2)

2
torch.Size([3, 2])
tensor([[7, 8],
        [2, 3],
        [3, 4]])
2
torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


In [22]:
tensor = torch.tensor([[[1,2,3],[2,3,4],[2,3,4]]])
print(tensor.ndim)
print(tensor.shape)
print(tensor)

3
torch.Size([1, 3, 3])
tensor([[[1, 2, 3],
         [2, 3, 4],
         [2, 3, 4]]])


In [24]:
#One of the common pitfalls apparently is that we access the wrong rank of our tensor
print(tensor[0])
#compare that with
print('\n')
print(tensor[0][0])

tensor([[1, 2, 3],
        [2, 3, 4],
        [2, 3, 4]])


tensor([1, 2, 3])


In [25]:
random_tensor = torch.rand(3,4)
#create a random tensor with 3 rows and 4 columns
#useful for the starting tensors for neural networks.
print(random_tensor)

tensor([[0.1559, 0.0603, 0.5996, 0.1962],
        [0.2480, 0.0566, 0.2460, 0.4082],
        [0.1172, 0.3996, 0.7679, 0.7855]])


In [29]:
## zeroes and ones, zeroes is useful to mask bits
zero = torch.zeros(3,1)
print(zero * random_tensor)


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [30]:
#ones explanation was skipped as they're solemnly used
ones = torch.ones(3,4)

In [31]:
one_to_ten = torch.arange(1,11,1) #it takes, start, end, steps, it's similar to the range() function in python
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
#tensors.'x'_like method returns a ones or zeroes  tensor that has the same shape as the input tensor with the values there.
zeroeslike = torch.zeros_like(one_to_ten)
zeroeslike

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
#tensors with specific datatypes, the tensor creating methods take in the dtype argument to specify the dtype. The specific name for the dtypes you can just look up
float32tensor = torch.tensor([[3.0,34,3.3],[23,4,4]],
                             dtype = None,
                             device=None,
                             requires_grad=False)
float32tensor.dtype

torch.float32

##Big 3 Errors we'll probably run in with Tensor Attributes
1. tensors with not the right datatype (verify with tensor.dtype)
2. tensors not right shape (verify with tensor.shape)
3. tensors not on right device (verify with tensor.device)


##other things
1. surprisingly a lot of int * floats do work but we just have to know that this could cause issues
2. devices refer to GPU and CPU

In [36]:
#we can typecase tensors using the following. 'tensorname.type(dtype)'
float16 = float32tensor.type(torch.float16)
float16.dtype


torch.float16

In [38]:
float16.device
float16.shape

torch.Size([2, 3])

##Operations
add, sub, multiply(element wise), divide, matrix multiplication.
total of 5 multiplications. Matrix multiplication and normal multiplication depend on the rank of the tensor.
. if we add/sub/multiply/divide a tensor it will do the operation so for all elements. So there goes 4 cases.
. Matrix Multiplications are matrix multiplications/dot products are shown in the second cell below

In [47]:
#operations are done twice to show diff ways of doing so
tensor = torch.arange(0,6)
print(tensor)
print('\n')
print(tensor +10)
print(torch.add(tensor,10))
print('\n')
print(tensor -10)
print(torch.sub(tensor,10))
print('\n')
print(tensor *10)
print(torch.mul(tensor,10))
print('\n')
print(tensor /10)
print(torch.div(tensor,10))

tensor([0, 1, 2, 3, 4, 5])


tensor([10, 11, 12, 13, 14, 15])
tensor([10, 11, 12, 13, 14, 15])


tensor([-10,  -9,  -8,  -7,  -6,  -5])
tensor([-10,  -9,  -8,  -7,  -6,  -5])


tensor([ 0, 10, 20, 30, 40, 50])
tensor([ 0, 10, 20, 30, 40, 50])


tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000])


In [98]:
#dot products/matrix multiplications are done in pytorch using the following
matrixA = torch.tensor([[1,2,3,4,5],[1,2,3,4,5]])
matrixB = torch.tensor([[1,2],
                        [3,4],
                        [5,6],
                        [7,8],
                        [9,0]])

print(matrixA.shape,matrixB.shape)
print('See how inner dimensions match but the shape is from the outer dimensions, that must follow broadcasting rules ')
print('\n')
print(torch.matmul(matrixA,matrixB)) #this is matrix multiplication
print(torch.mm(matrixA,matrixB)) #this is matrix multiplication
print(matrixA @ matrixB) #this is matrix multiplication

torch.Size([2, 5]) torch.Size([5, 2])
See how inner dimensions match but the shape is from the outer dimensions, that must follow broadcasting rules 


tensor([[95, 60],
        [95, 60]])
tensor([[95, 60],
        [95, 60]])
tensor([[95, 60],
        [95, 60]])


In [78]:
%%time
print(torch.matmul(matrixA,matrixB)) #this is matrix multiplication

tensor(70)
CPU times: user 1.24 ms, sys: 0 ns, total: 1.24 ms
Wall time: 1.04 ms


In [81]:
%%time
print(matrixA @ matrixB) #this is matrix multiplication

tensor(70)
CPU times: user 1.7 ms, sys: 36 µs, total: 1.73 ms
Wall time: 1.53 ms


Seems lilke using @ or matmul makes little difference on the time.

##Just as a easy heuristic for shape mismatch errors:
1. use .shape() and the shapes of the inner dimensions must match, in addition the outer dimensions will determine the shape of the matrix
2. If we have 2 tensors of the same shape, take the transpose of 1 to multiply them. This is shown below

In [102]:
matrixC = torch.rand(3,4)
matrixD = torch.rand(3,4)
print(f'matrix C is {matrixC}')
print(f'matrix D is {matrixD}')
print('\n')
#print(matrixC @ matrixD) <<--- causes error
matrixD2 = matrixD.T
print(f'multiplied we have {matrixC @ matrixD2} because we took the transpose of D')

matrix C is tensor([[0.5010, 0.0271, 0.5937, 0.8956],
        [0.0847, 0.1070, 0.6907, 0.8305],
        [0.2566, 0.4158, 0.9887, 0.9009]])
matrix D is tensor([[0.9485, 0.2286, 0.6674, 0.9758],
        [0.0411, 0.3020, 0.9770, 0.8334],
        [0.7172, 0.2579, 0.6943, 0.9842]])


multiplied we have tensor([[1.7515, 1.3551, 1.6599],
        [1.3762, 1.4027, 1.3852],
        [1.8774, 1.8528, 1.8643]]) because we took the transpose of D
